config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :candies_products

  resources :packings

  resources :candies

  resources :locations

  resources :products

  root 'home#index'

    get 'classic' => 'home#classic'
    get 'roshen' => 'home#roshen'
    get 'prestig' => 'home#prestig'
    get 'vip' => 'home#vip'
    get 'np' => 'home#np'
    get 'all' => 'home#all'
    get 'about_the_company' => 'home#about_the_company'
    get 'shares' => 'home#shares'
    get 'shipping_and_payment' => 'home#shipping_and_payment'
    get 'contacts' => 'home#contacts'

end

app/models/packing.rb
class Packing < ActiveRecord::Base

  has_attached_file :image, :styles => { :smal => "200x200>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
	has_and_belongs_to_many :products
end

app/controllers/packings_controller.rb
class PackingsController < ApplicationController
  before_action :set_packing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]
  # GET /packings
  # GET /packings.json
  def index
    @packings = Packing.all
  end

  # GET /packings/1
  # GET /packings/1.json
  def show
  end

  # GET /packings/new
  def new
    @packing = Packing.new
  end

  # GET /packings/1/edit
  def edit
  end

  # POST /packings
  # POST /packings.json
  def create
    @packing = Packing.new(packing_params)

    respond_to do |format|
      if @packing.save
        format.html { redirect_to @packing, notice: 'Packing was successfully created.' }
        format.json { render :show, status: :created, location: @packing }
      else
        format.html { render :new }
        format.json { render json: @packing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packings/1
  # PATCH/PUT /packings/1.json
  def update
    respond_to do |format|
      if @packing.update(packing_params)
        format.html { redirect_to @packing, notice: 'Packing was successfully updated.' }
        format.json { render :show, status: :ok, location: @packing }
      else
        format.html { render :edit }
        format.json { render json: @packing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packings/1
  # DELETE /packings/1.json
  def destroy
    @packing.destroy
    respond_to do |format|
      format.html { redirect_to packings_url, notice: 'Packing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_packing
      @packing = Packing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def packing_params
      params.require(:packing).permit(:image, :title, :description, :price)
    end
end

app/helpers/packings_helper.rb
module PackingsHelper
end

app/views/packings/_form.html.erb
<% if user_signed_in? %>
 <% if current_user.email == 'patreewigor@yandex.ru' %>


<%= form_for(@packing) do |f| %>
  <% if @packing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@packing.errors.count, "error") %> prohibited this packing from being saved:</h2>

      <ul>
      <% @packing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


 <% end %>
<% end %> 

app/views/packings/edit.html.erb
<h1>Editing Packing</h1>

<%= render 'form' %>

<%= link_to 'Show', @packing %> |
<%= link_to 'Back', packings_path %>

app/views/packings/index.html.erb
<% if user_signed_in? %>
 <% if current_user.email == 'patreewigor@yandex.ru' %>

<p id="notice"><%= notice %></p>

<h1>Listing Packings</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @packings.each do |packing| %>
      <tr>
        <td><%= image_tag packing.image, :width => 150, :height => 150 %></td>
        <td><%= packing.title %></td>
        <td><%= packing.description %></td>
        <td><%= packing.price %></td>
        <td><%= link_to 'Show', packing %></td>
        <td><%= link_to 'Edit', edit_packing_path(packing) %></td>
        <td><%= link_to 'Destroy', packing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Packing', new_packing_path %>

 <% end %>
<% end %> 

app/views/packings/new.html.erb
<h1>New Packing</h1>

<%= render 'form' %>

<%= link_to 'Back', packings_path %>

app/views/packings/show.html.erb
<div class="content-main">
<div class="line"></div>
      <table cellspacing="0" cellpadding="0" class="ctable">
        <tbody><tr>
          <td class="left">
            <div class="mtop">

            </div>
            <div class="list-block">
            <div class="tit"><a href="http://morozoff.by/">Новогодние упаковки</a></div>
              <ul class="list">
                <li><a href="/classic">Подарки Классик</a></li>
                <li><a href="/roshen">Подарки Рошен</a></li>
                <li><a href="/prestig">Подарки Престиж</a></li>
                <li><a href="/vip">Подарки VIP</a></li>
                <li><a href="/np">Новогодняя упаковка</a></li>

              </ul>
            </div>
            <div class="mbot"></div>
            <!--
            <br/>
            <div class="mtop"></div>
            <div class="list-block">
            <div class="tit"><a href="novogodnyaya-upakovka.php">Новогодняя упаковка</a></div>
              <ul class="list">
                <li><a href="upakovka-iz-kartona.php">Упаковка из картона</a></li>
                <li><a href="upakovka-iz-mikrogofrokartona.php">Упаковка из гофрокартона</a></li>
                <li><a href="upakovka-iz-jesti.php">Упаковка из жести</a></li>
                <li><a href="upakovka-iz-dereva.php">Упаковка из дерева</a></li>
                <li><a href="upakovka-tuby.php">Картонные тубы</a></li>
              </ul>
            </div>
            <div class="mbot"></div>
            -->
            <br>
<!--             <div class="dostavka">
              <a href="http://morozoff.by/dostavka.php" target="_blank" title="Доставка новогодних подарков">
                <img src="./Саквояж - 300 гр - Morozoff_files/dostavka.jpg" alt="Доставка новогодних подарков по Беларуси">
              </a>
            </div>
            <div class="catalog-l">
              <a href="http://morozoff.by/catalog.pdf" target="_blank" title="Каталог новогодних подарков">
                <img src="./Саквояж - 300 гр - Morozoff_files/catalog.jpg" alt="Каталог новогодних подарков">
              </a>
            </div> -->
            <br>          </td>
          <td class="right">
            <div class="navi">
              <a href="/all">Новогодние подарки</a> » <%= @packing.title %>
            </div>
            <div class="line-inner"></div>
              <div id="img_for_show">
                <%= image_tag @packing.image, :width => 350 %>
              </div>


              <h1><%= @packing.title %></h1>
            <div id="description_text">
              <br><%= @packing.description.html_safe %><br>
            </div>
              <div class="price"> <%= @packing.price %> бел.руб <span style="font-size:60%; color:#000;"></span></div>
              <div class="clear"></div>
            </form>





          </td>
        </tr>
      </tbody>

      </table>